spring:
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://116.62.193.96/pay?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 1

  jpa:
    show-sql: true

  rabbitmq:
    host: 116.62.193.96
    port: 5672
    publisher-confirms: true
    virtual-host: /

person:
  name: devid
  age: 20